<a href="https://colab.research.google.com/github/rahul-singh2021/machine_learning/blob/main/Bank_customer_churn_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [18]:
df=pd.read_csv("/content/Bank Customer Churn Prediction (1).csv")

In [19]:
df.head()

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [20]:
df.shape

(10000, 12)

In [21]:
df.columns

Index(['customer_id', 'credit_score', 'country', 'gender', 'age', 'tenure',
       'balance', 'products_number', 'credit_card', 'active_member',
       'estimated_salary', 'churn'],
      dtype='object')

In [22]:
dummies=pd.get_dummies(df.country)

In [25]:
merge=pd.concat([df,dummies],axis='columns')
df1=merge.drop(['country','France'],axis='columns')

In [26]:
df1

,customer_id,credit_score,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,Germany,Spain
0,15634602,619,Female,42,2,0.00,1,1,1,101348.88,1,0,0
1,15647311,608,Female,41,1,83807.86,1,0,1,112542.58,0,0,1
2,15619304,502,Female,42,8,159660.80,3,1,0,113931.57,1,0,0
3,15701354,699,Female,39,1,0.00,2,0,0,93826.63,0,0,0
4,15737888,850,Female,43,2,125510.82,1,1,1,79084.10,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,771,Male,39,5,0.00,2,1,0,96270.64,0,0,0
9996,15569892,516,Male,35,10,57369.61,1,1,1,101699.77,0,0,0
9997,15584532,709,Female,36,7,0.00,1,0,1,42085.58,1,0,0
9998,15682355,772,Male,42,3,75075.31,2,1,0,92888.52,1,1,0
9999,15628319,792,Female,28,4,130142.79,1,1,0,38190.78,0,0,0

In [27]:
df.isnull().sum()

customer_id         0
credit_score        0
country             0
gender              0
age                 0
tenure              0
balance             0
products_number     0
credit_card         0
active_member       0
estimated_salary    0
churn               0
dtype: int64

In [28]:
df1['gender'][df1['gender']=='Female']= 0
df1['gender'][df1['gender']=='Male']= 1

<ipython-input-28-04d53a477dae>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['gender'][df1['gender']=='Female']= 0
<ipython-input-28-04d53a477dae>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['gender'][df1['gender']=='Male']= 1

In [29]:
df1

,customer_id,credit_score,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,Germany,Spain
0,15634602,619,0,42,2,0.00,1,1,1,101348.88,1,0,0
1,15647311,608,0,41,1,83807.86,1,0,1,112542.58,0,0,1
2,15619304,502,0,42,8,159660.80,3,1,0,113931.57,1,0,0
3,15701354,699,0,39,1,0.00,2,0,0,93826.63,0,0,0
4,15737888,850,0,43,2,125510.82,1,1,1,79084.10,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,771,1,39,5,0.00,2,1,0,96270.64,0,0,0
9996,15569892,516,1,35,10,57369.61,1,1,1,101699.77,0,0,0
9997,15584532,709,0,36,7,0.00,1,0,1,42085.58,1,0,0
9998,15682355,772,1,42,3,75075.31,2,1,0,92888.52,1,1,0
9999,15628319,792,0,28,4,130142.79,1,1,0,38190.78,0,0,0

In [32]:
x=df1.drop(['churn'],axis='columns')
y=df[['churn']]

In [52]:
x

,customer_id,credit_score,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,Germany,Spain
0,15634602,619,0,42,2,0.00,1,1,1,101348.88,0,0
1,15647311,608,0,41,1,83807.86,1,0,1,112542.58,0,1
2,15619304,502,0,42,8,159660.80,3,1,0,113931.57,0,0
3,15701354,699,0,39,1,0.00,2,0,0,93826.63,0,0
4,15737888,850,0,43,2,125510.82,1,1,1,79084.10,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,771,1,39,5,0.00,2,1,0,96270.64,0,0
9996,15569892,516,1,35,10,57369.61,1,1,1,101699.77,0,0
9997,15584532,709,0,36,7,0.00,1,0,1,42085.58,0,0
9998,15682355,772,1,42,3,75075.31,2,1,0,92888.52,1,0
9999,15628319,792,0,28,4,130142.79,1,1,0,38190.78,0,0

In [54]:
y

      churn
0         1
1         0
2         1
3         0
4         0
...     ...
9995      0
9996      0
9997      1
9998      1
9999      0

[10000 rows x 1 columns]

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [47]:
model=LogisticRegression()

In [48]:
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [49]:
model.score(x_test,y_test)

0.7996

In [53]:
model.predict([[	15737888,	850,	0,	43,	2,	125510.82,	1,	1,	1,	79084.10,	0,	1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])